agents:
  programming:
    type: "aider"
    max_retries: 8
    model: "o1-mini"
    model_settings:
      edit_format: "diff"
      verify_ssl: true
      timeout: 120
      max_chat_history_tokens: 100000
  testing:
    type: "aider"
    model: "o1-mini"

logging:
  tdac:
    level: INFO
    color: green
  other_packages:
    level: "INFO"