general:
  type: "aider"
  max_retries: 4
  max_retries_protoblock_creation: 4
  total_timeout: 600
  use_file_summaries: true
  summarizer_timeout: 45  # Timeout in seconds for file summarization
  plausibility_check: true  # Whether to perform plausibility check after implementation
  halt_after_fail: false # Wait for the user to press Enter before starting the next attempt

aider:
  model: "openai/o3-mini"
  # model: "deepseek/deepseek-reasoner"
  model_settings:
    edit_format: "diff"
    verify_ssl: true
    timeout: 240
    max_chat_history_tokens: 200000

llm_strong:
  # provider: "deepseek"
  # model: "deepseek-reasoner"
  provider: "openai"
  model: "o3-mini"
  settings:
    temperature: 0.7
    max_tokens: null
    verify_ssl: true
    timeout: 120

llm_weak:
  provider: "openai"
  model: "o3-mini"
  settings:
    temperature: 0.7
    max_tokens: null
    verify_ssl: true
    timeout: 120

git:
  auto_commit_if_success: true

logging:
  tac:
    level: "DEBUG"
    color: "green"
  other_packages:
    level: "INFO"
