agents:
  programming:
    type: "aider"
    max_retries: 2
    model: "deepseek/deepseek-chat"
    model_settings:
      edit_format: "diff"
      verify_ssl: true
      timeout: 120
      max_chat_history_tokens: 200000
  testing:
    type: "aider"
    model: "deepseek/deepseek-chat"

llm:
  provider: "deepseek"  # or "openai"
  model: "deepseek-chat"  # model name for the selected provider
  settings:
    temperature: 0.7
    max_tokens: null  # null for no limit
    verify_ssl: true
    timeout: 120

git:
  auto_push: true

logging:
  tdac:
    level: DEBUG
    color: green
  other_packages:
    level: "INFO"
