agents:
  programming:
    type: "aider"
    max_retries: 4
    model: "deepseek"
    model_settings:
      edit_format: "diff"
      verify_ssl: true
      timeout: 120
      max_chat_history_tokens: 100000
  testing:
    type: "aider"
    model: "deepseek"

logging:
  tdac:
    level: DEBUG
    color: green
  other_packages:
    level: "INFO"