general:
  type: "aider"
  max_retries: 2
  total_timeout: 600

aider:
  model: "openai/o1-mini"
  model_settings:
    edit_format: "diff"
    verify_ssl: true
    timeout: 120
    max_chat_history_tokens: 200000

llm:
  provider: "openai"
  model: "o1-mini"
  settings:
    temperature: 0.7
    max_tokens: null
    verify_ssl: true
    timeout: 120

git:
  auto_push: true

logging:
  tdac:
    level: INFO
    color: green
  other_packages:
    level: "INFO"
