[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "test_chain"
version = "0.1.0"
description = "An Automated, Test-Driven AI Coding Framework"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
dependencies = [
    "pytest>=8.0.0",
    "aider-chat>=0.18.0",
    "PyYAML>=6.0.1",
]

[project.scripts]
test-chain = "test_chain.cli.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/test_chain"]